# Generated by Django 5.2.6 on 2025-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_type', models.CharField(choices=[('federal', 'Federal Program'), ('state', 'State Program'), ('ngo', 'NGO'), ('other', 'Other')], max_length=50)),
                ('whatsapp', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshots', models.FileField(blank=True, null=True, upload_to='scam_screenshots/')),
                ('description', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=150, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
